spring:
  application:
    name: products

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
#    url: jdbc:mysql://localhost:3306/ecommerce_platform
    url: jdbc:mysql://mysql:3306/ecommerce_platform
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  messages:
    basename: messages

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/enterprise_management

server:
#  address: 0.0.0.0
  port: 8332

angular:
  endpoint: http://localhost:4200